name: deploy-container

on:
  pull_request:
    branches:
      - main
    paths:
      - "marketing/container/**"
    types: [closed]
  workflow_dispatch:

defaults:
  run:
    working-directory: marketing/container

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install NPM dependencies
        run: npm ci

      - name: build app
        run: npm run build:prod

      - name: Yandex object storage static website
        uses: nekitcorp/yandex-storage-website-action@v2
        with:
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.BUCKET }}
          working-directory: ./dist
          clear: true
