name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - "marketing/container/**"
  workflow_dispatch: 


defaults:
  run:
    working-directory: marketing/container

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install NPM dependencies
        run: npm install

      - name: build app
        run: npm run build:prod

      - name: Yandex.Cloud Object Storage Upload (S3)
        uses: MrMeison/yc-object-storage-action@1.2.1
        with:
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.SECRET_ACCESS_KEY }}
          bucketName: ${{ secrets.BUCKET }}
          sourceDir: ./dist
          clear: true
