name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - "marketing/container/**"
  workflow_dispatch:
  pull_request:
    types:
      - closed

defaults:
  run:
    working-directory: marketing/container

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: install NPM dependencies
        run: npm install

      - name: build app
        run: npm run build:prod

      - name: Yandex Object Storage Action
        uses: MrMeison/yc-object-storage-upload-action@main
        with:
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.SECRET_ACCESS_KEY }}
          bucketName: ${{ secrets.BUCKET }}
          sourceDir: dist
          clear: true
