name: deploy-container

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "marketing/container/**"
      - "workflows/container.yml"
    types: [closed]

defaults:
  run:
    working-directory: marketing/container

jobs:
  deploy:
    if: ${{ github.event_name }} == "workflow_dispatch" ||
      ${{ github.event_name }} == "pull_request" && ${{github.event.pull_request.merged }} == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install NPM dependencies
        run: npm ci

      - name: build app
        run: npm run build:prod

      - name: Yandex Object Storage Action
        uses: povetek/yandex-object-storage-action@v3
        with:
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.BUCKET }}
          path: dist
          clear: true
